### ISSUE TITLE
Can't access localhost:3000 - Error message in logs

### ISSUE THREAD

**Issue by SheriffOfNotts** [danopstech/starlink#1]
Installed on docker and all containers running. I can't access localhost:3000 and when looking at grafana logs:

GF_PATHS_DATA='/var/lib/grafana' is not writable.
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later

**Comment by dwillcocks** [comment]
Hi, This is because of the file/folder permissions.

You need to change the owner of the `./data/grafana` folder on your host machine to match the uid the Grafana container is running as.

```
chown -R 472 ./data/grafana
```

I will look to commit a permanent fix into the repo. 

_Reference: https://linuxize.com/post/linux-chown-command/_

**Comment by SheriffOfNotts** [comment]
Hi thanks for your quick reply. FYI I'm running this on a Synology. Sorry for the dumb questions, but how to I find the uid of the grafana container and where is the ./data/grafana folder?

**Comment by dwillcocks** [comment]
Its a relative path, so your need to run the command from the repository root

**Comment by SheriffOfNotts** [comment]
Thanks for the info, but still got problems :( Sorry to be a pain..

These are the steps I've taken..

1. Copied the contents of the zip file to my docker folder
2. Ran the "chown -R xxx ./data/grafana" - no error

xxx@Server:/$ cd /volume1/docker
xxx@Server:/volume1/docker$ cd starlink-main
xxx@Server:/volume1/docker/starlink-main$ docker-compose pull && docker-compose up --remove-orphan
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
xxx@Server:/volume1/docker/starlink-main$ sudo docker-compose pull && docker-compose up --remove-orphan
Password: 
Pulling starlink_exporter  ... done
Pulling speedtest_exporter ... done
Pulling blackbox           ... done
Pulling prometheus         ... done
Pulling grafana            ... done
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
xxx@Server:/volume1/docker/starlink-main$

**Comment by SheriffOfNotts** [comment]
No idea why, but tried re-installing and all works. Fab tool - thanks for your help.
