### ISSUE TITLE
starlink_exporter

### ISSUE THREAD

**Issue by cristopherchandia** [danopstech/starlink#15]
hello 

I can't see the starlink data in graphana, the message is as follows:

There's an error in your script:
TypeError: Cannot read property 'fields' of undefined - line 3:28 (Check your console for more details)

on the console:

starlink_exporter_1 | time = "2021-07-14T16: 23: 50Z" level = error msg = "failed to collect context from dish: rpc error: code = Unimplemented desc = Unimplemented: <nil>" source = "exporter.go: 293"

can you help me please?
Thank you very much for this contribution!

**Comment by thinkspill** [comment]
The debug endpoint has changed from...

http://192.168.100.1/support/debug

...to...

http://192.168.100.1/support/advanced/debug

**Comment by dwillcocks** [comment]
Starlink have added authentication to some gRPC endpoints we was using. There is currently a work around inplace to collect what we can: https://github.com/danopstech/starlink_exporter/issues/32

Have you updated to latest running containers by running following commands?
```
docker-compose pull
docker-compose restart
```

**Comment by dwillcocks** [comment]
Also what dish software version do you have? maybe they have pushed more changes to the gRCP endpoint

**Comment by thinkspill** [comment]
Thanks Dan, it's working again after pulling and --force-recreate'ing.

**Comment by cristopherchandia** [comment]
This is the software version d61f015c-556a-42b4-ac91-d8e41d157871.release

**Comment by SheriffOfNotts** [comment]
Hi Dan, I’ve just tried this and I’m getting the enclosed error:

I’m on firmware 2bc83694-2dec-48c8-9061-88b86cdd5d89.uterm.release

**Comment by dwillcocks** [comment]
> This is the software version d61f015c-556a-42b4-ac91-d8e41d157871.release

According to this unofficial version tracker thats an old version. might be worth raising a support case to see why you have not moved onto the *.uterm.release versions?

https://docs.google.com/spreadsheets/d/1nsdLZ34VVX1qNVlDlAErzLov-fb_ZWgpYAQJWp_W8ic/edit#gid=383580049

**Comment by dwillcocks** [comment]
> I’m on firmware 2bc83694-2dec-48c8-9061-88b86cdd5d89.uterm.release

@SheriffOfNotts snap, bit of luck I'm currently on the same version.

So you have ran following in the starlink folder?
```
docker-compose pull
docker-compose restart
```

and what error message are you seeing?

**Comment by SheriffOfNotts** [comment]
Hi, yes I've upgraded as per the above instructions. I'm seeing the enclosed error.
![Screenshot 2021-07-15 at 13 43 40](https://user-images.githubusercontent.com/16319499/125790024-9a001b4d-5886-48cb-a440-6ef0fc747712.png)

**Comment by dwillcocks** [comment]
Looks like thats a Grafana plugin issue, "ae3e-plotly-panel" is a third party plugin I use to render the radar map. I will look into why this has broken tonight.

To confirm you are getting other metrics on the dashboard, like upload and download graphs are still working?

**Comment by SheriffOfNotts** [comment]
Yes, everything else is working.

Hope you don’t mind me asking, but have you had chance to look at changing the speedtest  location?

**Comment by dwillcocks** [comment]
I don't see the same error locally, so lets try getting a fresh copy of the plugin:

1. 
```
docker-compose down
````

2. Empty the data/grafana directory
![Screen Shot 2021-07-16 at 09 39 55](https://user-images.githubusercontent.com/4237699/125919492-56172d78-736d-409b-a506-581b51b19e2a.jpg)

3.
```
docker-compose pull && docker-compose up --remove-orphan
```

**Comment by SheriffOfNotts** [comment]
Hi Dan, I’ve followed the steps and also rebooted, but getting the same error?

**Comment by dwillcocks** [comment]
Can you try a different browser, have any ad/js/privacy blockers installed?, I'm going to look at producing the same nice obstruction map now available in the app, that might remove the requirement to need ae3e-plotly-panel

**Comment by SheriffOfNotts** [comment]
I’ve tried in Edge (Mac) and Safari and same result. The obstruction map sounds great. Do you think you will be able to speedtest server in the future?

**Comment by cristopherchandia** [comment]
Hi Dan
As I had been told before, it was a matter of updating the firmware of the antenna. I have been updated to version 2bc83694-2dec-48c8-9061-88b86cdd5d89.uterm.release, now graphana shows me the antenna data.
Thank you! :)
