### ISSUE TITLE
Connect to App with router in Bypass mode

### ISSUE THREAD

**Issue by Ubique88** [danopstech/starlink#23]
**Is your feature request related to a problem? Please describe.**
Unsure if it will be possible but can we still pull all these stats while the router is in bypass mode?

**Describe the solution you'd like**
Be able to use this app to pull stats while the router is in bypass mode.

**Describe alternatives you've considered**
Not running in bypass mode.

**Additional context**
I am going to be running a standard internet connection and starlink through a Firewall so the router will be in bypass mode.

**Comment by ghost** [comment]
I am also struggling with this. I hope someone can figure out how to connect to the router in bypass mode. Starlinks app still connects, so there has to be a way! 192.168.100.1 does not seem to work with the recent router code in bypass mode.

**Comment by fireblade-nz** [comment]
Try a wireshark packet capture on the device or as you're using bridge mode I assume you have a network that you can port mirror and thus see what the traffic (packets) are that the app is sending.

If you need someone to check the packet capture post it and sing out just only capture the traffic from the device (with no other apps open to reduce packet capture noise).

**Comment by brett-todd** [comment]
@Ubique88 / @jbandy88  The following wiki potentially has the detail you require to establish connectivity with the recent router code via different firewall appliances:

https://github.com/starlink-community/knowledge-base/wiki

**Comment by fleabeard** [comment]
When the router is in bypass it will only respond to hosts with an address in the 192.168.100.0/24 subnet. Here's two options.

- Add a secondary IP in the 192.168.100.0/24 subnet to the WAN interface of your router and NAT all traffic destined to 192.168.100.1 to that address. The link that @brett-todd posted will help you do this.
- Add an interface to your docker hardware connected to a switch or VLAN with the Starlink router and your router's WAN interface. Set up a MacVLAN in docker with an address in 92.168.100.0/24 and add that network to the exporter container.

**Comment by fireblade-nz** [comment]
+1 for the 2nd Option as its been working great for our setup for a couple
months.  DHCP on the bridge interface & the bridged Starlink VLAN trunked
to the server running the docker instance.

Will migrate to DHCP with NAT after replacing the L3 device plugged into
dishy.

Thanks for your help
