### ISSUE TITLE
Cannot contact developer

### ISSUE THREAD

**Issue by fpolicelli** [danopstech/starlink#32]
dan@danops.tech does not work for me.  Can you provide another email address

**Comment by sinnx3** [comment]
> [dan@danops.tech](mailto:dan@danops.tech) does not work for me. Can you provide another email address

I think it's safe to say @dwillcocks has abandoned this project seeing as there's been no update since mid 2021 and broken features that still work (obstruction mapping) haven't been patched and I myself have tried contacting him via (email,github,twitter) to no avail, so if any aspiring dev's willing to maintain/update/upgrade this I would say a lot of people whom aren't technologically inclined (myself being one) enough to run sparky's version due to lack of instructional guidance would be very appreciative.

I'd be willing to chip in a couple $ via a github sponsor or Ko-Fi so long as it's being actively maintained.

- Sinnx3 (Discord: Sinnx3#0231 - Can actively be found in the r/starlink community discord)

**Comment by dwillcocks** [comment]
Hi, sorry, yes that email does not exist anymore, and my twitter aswell. 

I will endeavour to find some time to revisit this project with my day job and personal (non tech) projects taking lots of my time. I will make some time to update the exporter and work through all the things Starlink no longer give open access too via grpc.

I'm on the original v1 dish, so can only work with that dish's hardware and grpc spec I have at hand.

**Comment by sinnx3** [comment]
> Hi, sorry, yes that email does not exist anymore, and my twitter aswell.
> 
> I will endeavour to find some time to revisit this project with my day job and personal (non tech) projects taking lots of my time. I will make some time to update the exporter and work through all the things Starlink no longer give open access too via grpc.
> 
> I'm on the original v1 dish, so can only work with that dish's hardware and grpc spec I have at hand.

@dwillcocks I can provide GRPC data for both rev2_proto2 (round dish) and rev3_proto2 (rectangle dish) if you need it and I'm sure @virtuallynathan would be more than willing to help provide data from his 3 dishes.

**Comment by fpolicelli** [comment]
Hi Dan,
I am very glad to be in touch with you.
I am part of a small group of NASA scientists interested in research on the use of Starlink (and other) Signal-to-Noise Ratio (SNR) data to retrieve precipitation rate information. I have not been able to get Starlink’s interest in selling me the data (Perhaps because we are interested in a small cost experiment to start things). However, there is the possibility that we may be able to expand this to a global system in the future, in which case hopefully Starlink will be interested. In the meantime, I have talked to NASA legal counsel, and they have advised me that we can read data from a dish that we own. It would be great if we could install a dish on the roof of our Earth sciences building, along with an existing array of other rain measuring/weather instruments.

One concern I have is that it seems Starlink has done something to disable reading SNR. I am under the impression that this only affects new dishes, but I am not entirely sure. If that is the case and cannot be remedied, please let me know if you would be willing to sell (or perhaps loan)** us your dish for the benefit of Science (assuming it is in reasonable condition and can read SNR), or partner with us in some other way on this experiment.  I am cc’ing Darryl Mitchell in our partnerships office in case we need to ask him any questions about a partnering arrangement.

Other concerns I have include (1) whether random inaccuracies in pointing at the satellites or (2) inter-satellite differences in transmitting power will substantially interfere with our ability to retrieve precipitation rate based on the change in SNR caused by precipitation. It may be that the only way to find out is to do an experiment.

Please let me know your thoughts on this,
Frederick “Fritz” Policelli
NASA, Goddard Space Flight Center

** Please note that as the scientist on this work, I am not able to commit the government to purchasing anything at this time. I would first have to secure the funding and then abide by standard government procurement rules, which are a function of the cost of an item (relatively easy for small procurements).



From: Daniel Willcocks ***@***.***>
Reply-To: danopstech/starlink ***@***.***>
Date: Wednesday, January 18, 2023 at 3:44 PM
To: danopstech/starlink ***@***.***>
Cc: "Policelli, Frederick S. (GSFC-6170)" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [danopstech/starlink] Cannot contact developer (Issue #32)


Hi, sorry, yes that email does not exist anymore, and my twitter aswell.

I will endeavour to find some time to revisit this project with my day job and personal (non tech) projects taking lots of my time. I will make some time to update the exporter and work through all the things Starlink no longer give open access too via grpc.

I'm on the original v1 dish, so can only work with that dish's hardware and grpc spec I have at hand.

**Comment by virtuallynathan** [comment]
> I am under the impression that this only affects new dishes, but I am not entirely sure. 

All of the dishes remotely update their firmware, anything that hasn't updated since the SNR value was removed simply won't work at all anymore. There's no way to hold back or downgrade the firmware.

**Comment by dwillcocks** [comment]
The dish is playing very hard to get. I am working on it, but it will take some time. as my spare time is very short currently too.
