### ISSUE TITLE
Grafana admin password not working

### ISSUE THREAD

**Issue by EQXTFL** [danopstech/starlink#4]
Hi, had to reset the password to make it work, can you please verify if it is set correctly.

If anyone needs to reset as well:
`docker exec -ti <container ID> grafana-cli admin reset-admin-password admin`

**Comment by dwillcocks** [comment]
I do not set the username and password, It should be using the default from the upstream Grafana container. I did upgrade Grafana from v7.5.4 -> v7.5.5, so will check if the defaults changed, or the minor upgrade causes an issue.

**Comment by dwillcocks** [comment]
Another Grafana is due, I will test the upgrade locally first
