### ISSUE TITLE
Speedtest frequency and server

### ISSUE THREAD

**Issue by SheriffOfNotts** [danopstech/starlink#7]
Last questions :)

Is is possible to amend the frequency and specify the server?

**Comment by dwillcocks** [comment]
Speed test interval can be adjusted here: https://github.com/danopstech/starlink/blob/main/config/prometheus/prometheus.yml#L14-L15

I have an open issue on the speedtest exported repo to add picking server ID: https://github.com/danopstech/speedtest_exporter/issues/3

**Comment by SheriffOfNotts** [comment]
Sorry completely missed that :)

It really is a great tool - thanks for all your hard work..

**Comment by SheriffOfNotts** [comment]
Hi Daniel, I noticed that this has been closed - is it not possible?

**Comment by dwillcocks** [comment]
Picking the server ID feature will be tracked by an issue on the exporters repo here: https://github.com/danopstech/speedtest_exporter/issues/3
