### ISSUE TITLE
Data Mismatch

### ISSUE THREAD

**Issue by SheriffOfNotts** [danopstech/starlink#8]
Hi just looking at the data and (it may well be me), but there appears to be a mismatch - 127mb/s shown as the best in the table on the top right and 167mb/s on the rows at the bottom?

<img width="764" alt="Screenshot 2021-05-08 at 17 24 20" src="https://user-images.githubusercontent.com/16319499/117546490-929be900-b022-11eb-93c0-79972b48f55f.png">
<img width="867" alt="Screenshot 2021-05-08 at 17 24 26" src="https://user-images.githubusercontent.com/16319499/117546493-94fe4300-b022-11eb-9dbb-38df53e15532.png">

**Comment by dwillcocks** [comment]
Did it align?

**Comment by dwillcocks** [comment]
Yes I get the same, after a reboot Starlink reports more obstructions then before. over next 24/28hours the data ages out and it shows the ongoing obstructions that I know about.
